# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0005_auto_20160902_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('creating_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='people.Person')),
                ('receiving_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_events', to='people.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, choices=[('birthday', 'birthday'), ('anniversary', 'anniversary'), ('religious', 'religious'), ('geopolitical', 'geopolitical')], max_length=30, null=True)),
                ('date_start', models.DateField()),
                ('time_start', models.TimeField(blank=True)),
                ('is_default_event', models.BooleanField(default=True)),
                ('is_reoccuring_yearly', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
