# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-05 03:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedevent',
            name='creating_person',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_events',
                to='people.Person'),
        ),
        migrations.AddField(
            model_name='associatedevent',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_events',
                to='events.Event'),
        ),
        migrations.AddField(
            model_name='associatedevent',
            name='receiving_person',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='received_events',
                to='people.Person'),
        ),
    ]
