# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_createdevent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
