# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170516_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='is_externally_visible',
            field=models.BooleanField(default=True),
        ),
    ]
