# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-05 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170205_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
