# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170120_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(blank=True, default='', max_length=40),
        ),
    ]
