# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170204_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-datetime_updated'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ManyToManyField(to='events.EventType'),
        ),
    ]
