# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170204_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatedevent',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='associatedevent',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_types',
            field=models.ManyToManyField(related_name='events', to='events.EventType'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
