# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_transaction_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
