# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20170207_0138'),
        ('transactions', '0002_transaction_stripe_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiving_person',
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transactions',
                to='people.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='associated_event',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transactions',
                to='events.AssociatedEvent'),
        ),
    ]
