# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20170120_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
