# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20170207_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='shipping_address',
            new_name='associated_location',
        ),
    ]
