# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170514_0312'),
        ('transactions', '0004_auto_20170209_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='associated_event_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='events.EventDate'),
        ),
    ]
