# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationshiptype',
            name='from_person_female_display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='to_person_female_display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='to_person_male_display_name',
            field=models.CharField(max_length=100),
        ),
    ]
