# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20160902_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-datetime_updated']},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['-datetime_updated']},
        ),
        migrations.AlterField(
            model_name='person',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
