# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedlocation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_locations', to='people.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='associatedlocation',
            unique_together=set([('person', 'location')]),
        ),
    ]
