# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product_type', models.TextField(choices=[('card', 'card')], default='card', max_length=30)),
                ('main_image_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
