# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('product_type', models.TextField(choices=[('CARD', 'CARD')], default='CARD', max_length=30)),
                ('main_image_url', models.URLField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='events.Event')),
            ],
            options={
                'ordering': ('-datetime_updated',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductToEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventType')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'ordering': ('-datetime_updated',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='event_types',
            field=models.ManyToManyField(through='products.ProductToEventType', to='events.EventType'),
        ),
    ]
