# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('product_type', models.TextField(choices=[('card', 'card')], default='card', max_length=30)),
                ('main_image_url', models.URLField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='events.Event')),
                ('event_types', models.ManyToManyField(to='events.EventType')),
            ],
            options={
                'ordering': ('-datetime_updated',),
                'abstract': False,
            },
        ),
    ]
