# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.TextField(choices=[('CARD', 'CARD')], default='CARD', max_length=30),
        ),
    ]
