# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170204_2213'),
        ('products', '0003_auto_20170120_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='events.Event'),
        ),
        migrations.AddField(
            model_name='product',
            name='event_types',
            field=models.ManyToManyField(to='events.EventType'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
